defaults:
  - image: hsimg

base_options:
  print_freq: 10
  epochs: 500
  save_model_freq: -1
  save_img_freq: 10
  do_fix_noise: True
  seed: 123456789
  debugging: False
  gpu_ids: [1]

models:
  model_name: "unet_256"
  input_nc: 1
  ngf: 64
  norm: batch
optimizer:
  algorithm: adam
  lr: 0.0002

hydra:
  run:
    dir: ../outputs/${image.name}/${image.type}-${models.model_name}-epochs=${base_options.epochs}-fix=${base_options.do_fix_noise}
